### ISSUE TITLE
Alert users of version compatibility/synchronization with new documentation

### ISSUE THREAD

**Issue by dshimo** [OpenLiberty/liberty-language-server#94]
noted in Liberty Tools for Eclipse README
- [x] #85, noting Eclipse compatibility with Lemminx Version (PR contains more details) noted in Liberty Tools for Eclipse README
- [x] #83, noting Eclipse compatibility with Lemminx Version

For LCLS readme
- [x] #90, requires latest ci.common library change, part of LMP 3.7 and LGP 3.5
  - noted in [README](https://github.com/OpenLiberty/liberty-language-server#liberty-dev-mode-schema-generation)
- [x] #101 , requires latest ci.common library change, not yet released (will be LMP 3.7.1 and LGP 3.5.1)

**Comment by evie-lau** [comment]
I believe the Eclipse compatibilities are sufficiently noted in the [Liberty Tools for Eclipse](https://github.com/OpenLiberty/liberty-tools-eclipse) project README, and do not need to be noted in this repo. May have to update the Eclipse repo when necessary.

**Comment by cherylking** [comment]
Updated the README for LMP 3.7.1 and LGP 3.5.1 recommendation now that they are released.
